### ISSUE TITLE
Add possibility to preload responsive images using data-img2picture-preload

### ISSUE THREAD

**Issue by ItsEthanH** [saneef/eleventy-plugin-img2picture#25]
Hello :)

Was wondering if it was possible to create a responsive preload <link> tag based on the presence of some attribute on <img> tags, such as `data-img2picture-preload`

I've seen how this can be done here:
https://web.dev/articles/preload-responsive-images

The issue is, that with the default way of naming images, the hash at the end of the image isn't guaranteed, and creating a responsive preload with these randomly generated hashes is difficult.

I could change the filenameFormatter option to use a more predictable filename, but this prevents the eleventy-img disk cache:
https://www.11ty.dev/docs/plugins/image/#disk-cache

Therefore, would it be possible to "map" the srcset/sizes attribute from the <img> tag, create a responsive <link> preload, and add that to the <head> of the associated html document, please?

I can try submitting a PR?

**Comment by saneef** [comment]
Hey @ItsEthanH, thanks for bringing this idea.  
Please do try out, and send a PR. 

I haven't really delved into the idea. But, here are some thoughts that popped in my head after reading your notes.

1. The `generateImage()` returns a string with generated `<picture>...<picture>` HTML. Maybe, we could return an object with `{ picture: "<picture>...", otherDataNeededForPrelodedTag: ""}`. This can be used later in the calling `replaceImages()` to generate `<link rel="preload" ... />` tags and inserted into the HTML document (`content`).
2. Since the plugin is made for different file formats for each image, like `avif`, `webp`, and `jpg`, which one can be used in the `<link rel="preload" ... />` tag? How can we figure out the `media` attribute? Is it possible from the `sizes` attribute?
3. If we have figured out the key things, a minor enhancement: we can insert the `<link rel="preload" ... />` tags at the end of `<head>` tag, _by default_. Additionally, we can allow users to use HTML comment like `<!-- img2picture:preload-tags -->` to pinpoint the location to insert the preload tags.

Cheers.
